# Generated by Django 3.1.7 on 2021-03-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='courier_id',
            new_name='courier',
        ),
    ]
