# Generated by Django 3.1.7 on 2021-03-15 07:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20210315_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='orders_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=[], size=None, verbose_name='id текущих заказов'),
        ),
    ]
