# Generated by Django 3.1.7 on 2021-03-15 08:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20210315_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='last_complete_time',
            field=models.DateTimeField(null=True, verbose_name='Время последней доставки'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='orders_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), null=True, size=None, verbose_name='id текущих заказов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='assign_time',
            field=models.DateTimeField(null=True, verbose_name='Время назначения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(null=True, verbose_name='Время доставки в секундах'),
        ),
    ]
