# Generated by Django 3.1.7 on 2021-03-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20210315_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='assign_time',
            field=models.DateTimeField(null=True, verbose_name='Время назначения'),
        ),
    ]
