# Generated by Django 3.1.7 on 2021-03-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_courier_assign_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='courier',
            new_name='courier_id',
        ),
    ]
