# Generated by Django 3.1.7 on 2021-03-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20210316_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='courier_id',
            new_name='courier',
        ),
    ]
